# .SILENT:

# to  generate migrations
#  param Name for migration desc
gen-db-migration:
	alembic revision --autogenerate -m "$(NAME)"
	

# to apply migrations 
apply-db:
	alembic upgrade head
	

# to generate requirements 
gen-req:
	uv pip freeze > requirements.txt


create_venv:
	uv venv

test:
	echo "hello world"



